# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'calls',
            },
        ),
    ]
