# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 01:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gateway',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('willing_to_receive_calls', models.BooleanField()),
                ('willing_to_be_call_hero', models.BooleanField()),
                ('willing_to_be_pin_hero', models.BooleanField()),
                ('last_used_phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('last_used_state', models.CharField(max_length=50)),
                ('last_used_gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.Gateway')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AlterModelTable(
            name='call',
            table='call',
        ),
    ]
