# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20180115_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('video_path', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'training_module',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.BooleanField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.TrainingModule')),
            ],
            options={
                'db_table': 'training_question',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_trained',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_up_to_date',
        ),
        migrations.AddField(
            model_name='user',
            name='read_articles',
            field=models.ManyToManyField(to='calls.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='training_completed',
            field=models.ManyToManyField(to='calls.TrainingModule'),
        ),
    ]
