# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_auto_20180115_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='read_articles',
            field=models.ManyToManyField(blank=True, to='calls.Article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='training_completed',
            field=models.ManyToManyField(blank=True, to='calls.TrainingModule'),
        ),
    ]
