# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20180117_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
