# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 21:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_auto_20180117_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller',
            old_name='location',
            new_name='region',
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='address_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='address_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='address_street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='address_unit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caller',
            name='address_zipcode',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='caller',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_used_phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
    ]
