# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20180118_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingmodule',
            old_name='video_path',
            new_name='video_url',
        ),
    ]
