# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_auto_20180118_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
