# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_auto_20180118_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supported_languages',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='willing_to_be_call_center_support',
            field=models.BooleanField(default=False),
        ),
    ]
