# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_auto_20180119_2117'),
        ('calls', '0007_auto_20180122_2157'),
    ]

    operations = [
    ]
