# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_merge_20180122_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='caller',
            name='last_name',
        ),
        migrations.AddField(
            model_name='caller',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
