# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_updated_gateway_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='agent_id',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='agent_id',
            new_name='external_gateway_id'
        ),
        migrations.AddField(
            model_name='gateway',
            name='active',
            field=models.BooleanField(default=True),
        )
    ]
