# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_gateway_add_active_change_agent_id_to_external_gateway_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFirstEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uii', models.CharField(max_length=30)),
                ('call_start', models.CharField(max_length=100)),
                ('enqueue_time', models.CharField(max_length=30)),
                ('dequeue_time', models.CharField(max_length=30)),
                ('queue_duration', models.CharField(max_length=30)),
                ('ani', models.CharField(max_length=30)),
                ('dnis', models.CharField(max_length=30)),
                ('outbound_disposition', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=30)),
                ('gate_id', models.CharField(max_length=30)),
                ('gate_name', models.CharField(max_length=30)),
                ('recording_url', models.CharField(max_length=500)),
                ('agent_id', models.CharField(max_length=30)),
                ('agent_username', models.CharField(max_length=30)),
                ('agent_phone', models.CharField(max_length=100)),
                ('agent_disposition', models.CharField(max_length=30)),
                ('sess_duration', models.CharField(max_length=30)),
                ('agent_externid', models.CharField(max_length=50)),
                ('agent_notes', models.TextField()),
            ],
        ),
    ]
