# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0016_FleshOutModels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_used_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
