# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0018_MakeFieldsNullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='old_id',
        ),
        migrations.AddField(
            model_name='user',
            name='cc_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cc_id'], name='IX_user_cc_id'),
        ),
    ]
