# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0019_Rename user PK'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
