# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0022_auto_20180419_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='read_articles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='training_completed',
        ),
    ]
