# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0023_Remove user join tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(to='calls.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_articles',
            field=models.ManyToManyField(blank=True, to='calls.Article'),
        ),
        migrations.AddField(
            model_name='user',
            name='training_completed',
            field=models.ManyToManyField(blank=True, to='calls.TrainingModule'),
        ),
    ]
