# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0024_Replace user join tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectfirstevent',
            name='call_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectfirstevent',
            name='dequeue_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectfirstevent',
            name='enqueue_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
