# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0025_auto_20180503_2246'),
        ('calls', '0025_make_cf_fields_nullable'),
    ]

    operations = [
    ]
