# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0026_merge_20180503_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_used_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.Gateway'),
        ),
    ]
